<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>G</string>
		<string>macro</string>
		<string>scp</string>
	</array>
	<key>name</key>
	<string>Syntec Macro</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^%@MACRO</string>
			<key>name</key>
			<string>keyword.control.header.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.syntec-macro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>comment.block.paren.syntec-macro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\(\*)</string>
			<key>end</key>
			<string>(\*\))</string>
			<key>name</key>
			<string>comment.block.stars.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(IF|THEN|ELSE|ELSEIF|END_IF)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(REPEAT|UNTIL|END_REPEAT)\b</string>
			<key>name</key>
			<string>keyword.control.repeat.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(WHILE|DO|END_WHILE)\b</string>
			<key>name</key>
			<string>keyword.control.while.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FOR|TO|BY|END_FOR)\b</string>
			<key>name</key>
			<string>keyword.control.for.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CASE|OF|END_CASE)\b</string>
			<key>name</key>
			<string>keyword.control.case.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GOTO|EXIT)\b</string>
			<key>name</key>
			<string>keyword.control.flow.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ABS|ACOS|ASIN|ATAN|ATAN2|COS|SIN|TAN|CEIL|FLOOR|ROUND|SQRT|EXP|LN|LOG|POW|MAX|MIN|SIGN|RANDOM|MOD)\b</string>
			<key>name</key>
			<string>support.function.math.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(STR2INT|SCANTEXT)\b</string>
			<key>name</key>
			<string>support.function.string.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(OPEN|CLOSE|PRINT|GETARG|GETTRAPARG|PARAM)\b</string>
			<key>name</key>
			<string>support.function.io.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(READDI|READDO|READABIT|SETDO|SETABIT|READRREGBIT|SETRREGBIT)\b</string>
			<key>name</key>
			<string>support.function.io.rw.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DBOPEN|DBCLOSE|DBNEW|DBLOAD|DBSAVE|DBINSERT|DBDELETE)\b</string>
			<key>name</key>
			<string>support.function.db.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ALARM|MSG|WAIT|SLEEP|SYSVAR|SYSDATA|DRVDATA|STD|STDAX)\b</string>
			<key>name</key>
			<string>support.function.system.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(CHKMN|CHKSN|CHKMT|CHKMI|CHKINF)\b</string>
			<key>name</key>
			<string>support.function.check.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PUSH|POP|STKTOP|AXID|INT)\b</string>
			<key>name</key>
			<string>support.function.misc.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(SETDRAW|DRAWHOLE)\b</string>
			<key>name</key>
			<string>support.function.draw.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>keyword.operator.assignment.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(AND|OR|XOR|NOT)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&gt;|&lt;=|&gt;=|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![A-Za-z0-9_])=(?!=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[A-Za-z_]\w*|@\d+|@\[.+?\]</string>
			<key>name</key>
			<string>variable.language.global.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[A-Za-z_]\w*|#[1-9]\d*|#\[.+?\]</string>
			<key>name</key>
			<string>variable.language.local.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(AR|MAR)\d+\b</string>
			<key>name</key>
			<string>variable.language.app.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bG\d+(?:\.\d+)?\b</string>
			<key>name</key>
			<string>entity.name.function.gcode.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bM\d+\b</string>
			<key>name</key>
			<string>entity.name.function.mcode.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bN\d+\b</string>
			<key>name</key>
			<string>entity.name.label.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(M99|M30|M02)\b</string>
			<key>name</key>
			<string>keyword.control.end.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bG65\b</string>
			<key>name</key>
			<string>keyword.other.call.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bG66(?:\.1)?\b</string>
			<key>name</key>
			<string>keyword.other.modal-call.syntec-macro</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.\d*\b</string>
			<key>name</key>
			<string>constant.numeric.float.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.syntec-macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(S|F|T|H|D|B|L|P|Q|R)\s*[+-]?\d*\.?\d+</string>
			<key>name</key>
			<string>entity.name.function.address.syntec-macro</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.syntec-macro</string>
	<key>uuid</key>
	<string>c7a1f8e0-4b2c-4d6e-9f3a-1b2c3d4e5f6a</string>
</dict>
</plist>
